### ISSUE TITLE
rpm4 failed to build on 10.10

### ISSUE THREAD

**Issue by Sarah-E-Greene** [stepanstipl/homebrew-noop#1]
I tried to install createrepo on my yosemite machine today, which requires RPM4.  This failed with the following:

https://gist.github.com/anonymous/1b4e28ccc7fec5f1b76e

**Comment by mahileeb** [comment]
I've got it to build by installing gcc-4.9 via hombrew then using the following patch to the formula: https://gist.github.com/mahileeb/9915814137760585620d

then built it via

```
HOMEBREW_CC=gcc-4.9 brew install rpm4
```

**Comment by stepanstipl** [comment]
Hi, I've just updated rpm version to 4.12.0.1 and hopefully fixed the issue you had (thanks @mahileeb ) + one more I've come across. Can you test and confirm it's working for you?

(works for me on Yosemite 10.10.2 both with default gcc and gcc-4.8 and gcc-4.9)

**Comment by mahileeb** [comment]
Confirmed working, thanks a lot!

**Comment by stepanstipl** [comment]
Thanks, I've tested this now on vanilla Yosemite with homebrew in standard path & system python. Seems to work fine.
