### ISSUE TITLE
rpmlint doesn't work on 10.10.5

### ISSUE THREAD

**Issue by mmalchuk** [stepanstipl/homebrew-noop#4]
```
# rpmlint
Traceback (most recent call last):
  File "/usr/local/bin/rpmlint", line 36, in <module>
    import Pkg
  File "/usr/local/lib/rpmlint/Pkg.py", line 29, in <module>
    import rpm
ImportError: No module named rpm
#
```

**Comment by stepanstipl** [comment]
Hi @mmalchuk,
have you followed this step in the readme/printed when you install the formulae? I know it's a bit hidden, but so far I haven't discovered better way.

> If you're using system Python, make sure Homebrew's site-packages are added to your Python sys.path:
> `mkdir -p /Users/$(whoami)/Library/Python/2.7/lib/python/site-packages`
> `echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/$(whoami)/Library/Python/2.7/lib/python/site-packages/homebrew.pth`

**Comment by mmalchuk** [comment]
Hi @stepanstipl, I don't use the system Python, instead of system I use pyenv with 2.7.10 by default.

**Comment by stepanstipl** [comment]
Hi, this repo is not maintained anymore, I would recommend using docker, for example `stepanstipl/centos7-rpm-devtools`.
