### ISSUE TITLE
Calling xxx#sha1 is deprecated!

### ISSUE THREAD

**Issue by pierrenicolasr** [stepanstipl/homebrew-noop#5]
Hi,
getting 
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/stepanstipl/homebrew-noop/createrepo.rb:7:in `class:Createrepo'
Please report this to the stepanstipl/noop tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/stepanstipl/homebrew-noop/createrepo.rb:7:in `class:Createrepo'
Please report this to the stepanstipl/noop tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/stepanstipl/homebrew-noop/createrepo.rb:7:in `class:Createrepo'
Please report this to the stepanstipl/noop tap!

when upgrading brew.

**Comment by stepanstipl** [comment]
Hi, this repo is not maintained anymore, I would recommend using docker, for example `stepanstipl/centos7-rpm-devtools`.
